### ISSUE TITLE
enable database error collection

### ISSUE THREAD

**Issue by marcesher** [cfpb/new-relic-installer#8]
We need to set the database error collector to true, not false

**Comment by sleitner** [comment]
In the last Security documentation that I have, I see a requirement for `newrelic.error_collector.record_database_errors=False`  and 
`newrelic.error_collector.enabled=True`. 

Are you saying that the former should be True? Can you double check this? (There is actually a typo in my ansible code that makes a change to `enabled` flag a no-op. I'll correct that, though the default for `enabled` is True so the stuff that is already installed will be fine).

**Comment by marcesher** [comment]
@sleitner Yup... there's a newer version of the doc that reflects changes I requested, one of them being this.
